### ISSUE TITLE
How to configure baraja-js in VueJS applications?

### ISSUE THREAD

**Issue by FernandoFHS** [nuxy/baraja-js#3]
I would like to have a clearer example of how to configure a VueJS component if possible.

I've done the import:

import Baraja from 'baraja-js';
import 'baraja-js/dist/css/baraja.css';

**Comment by nuxy** [comment]
You're in luck my friend. I have _ported the package_ to now support [Vue 3](https://v3.vuejs.org)

https://github.com/nuxy/vue-baraja-js

**Comment by FernandoFHS** [comment]
That is great! Thank you very much, your work is excellent
