### ISSUE TITLE
Keep the distance between 2 cards static

### ISSUE THREAD

**Issue by Hielkio** [nuxy/baraja-js#5]
I would love to use this for my card playing game, but I'm running into a problem.

As you can see in this example, the spacing between the cards is based on the width of the container instead of static / fixed:

https://i.imgur.com/dEZrpZt.png

I was expecting that the spacing was the same with 3 cards instead of 8.
Maybe this isn't the right solution for my project, but I'd love to hear if it is or isn't.

Anyways, great job you did! Keep up the good work!

**Comment by nuxy** [comment]
> I was expecting that the spacing was the same with 3 cards instead of 8.

Using the [default fan settings](https://github.com/nuxy/baraja-js/blob/master/src/baraja.js#L48) you should end up with the following result:

![example](https://user-images.githubusercontent.com/1234102/225177360-8e4cd266-1d72-485b-aa47-90121f0ef5c0.png)

If you want to override this behavior you can configure the [Fan options](https://github.com/nuxy/baraja-js#fan-options) during the initialization process:

```
const options = {
  easing:      'ease-out',
  direction:   'right',
  origin:      {x: 25, y: 100},
  speed:       500,
  range:       50,
  translation: 0,
  center:      true,
  scatter:     false
};

const baraja = new Baraja(container, options);
```

In your case, you can alter the card distance by decreasing the `range`

Hope this helps.
